<?php

$lang = array(
 'presentation'             => 'Présentation',
 'competence'               => 'Compétences',
 'experience'               => 'Expériences',
 'formation'                => 'Formations',
 'other'                    => 'Divers',
 'download'                 => 'Téléchargements',

 'knowledge_datapreocessing'=> 'Compétences Professionnelles',
 'experience_professionnel' => 'Expériences Professionnelles',
 'studies'                  => 'Formations',

 'programming_languages'    => 'Langages de Programmation',
 'operating_systems'        => 'Systémes d\'Exploitation',
 'system_administration'    => 'Administration Systéme',
 'databases'                => 'Base de Donnée',
 'method'                   => 'Méthode d\'Analyse',
 'software'                 => 'Logiciels',
 'API__TECHNO'              => 'API / Technologie',

 'concept'                  => 'notion',
 'schoolofcomputerengineer' => 'Ecole d\'ingénieur en informatique',
 'notfinishedformation'     => 'Formation non terminée',
 'businessdataprocessing'   => 'Informatique de Gestion',
 'during1years'             => 'pendant 1 ans',
 'technicalcommercial'      => 'Technico-Commercial',

 'nationality'              => 'Nationalité',
 'lastname'                 => 'Prenom',
 'firstname'                => 'Nom',
 'familysituation'          => 'Situation Familiale',
 'age'                      => 'Age',
 'birthdate'                => 'Date de Naissance',
 'birthplace'               => 'Lieu de Naissance',
 'address'                  => 'Adresse',
 'homephone'                => 'Téléphone Domicile',
 'portphone'                => 'Téléphone Portable',
 'email'                    => 'Courriel',
 'yearold'                  => 'ans',
 'company'                  => 'Société',
 'activity'                 => 'Activité',
 'technology'               => 'Technologie',
 'mission'                  => 'Mission',
 'language'                 => 'Langue',
 'english'                  => 'Anglais',
 'spanish'                  => 'Espagnol',
 'school'                   => 'Scolaire',
 'technical'                => 'Technique',
 'licence'                  => 'Permis',
 'moto'                     => 'Moto',
 'car'                      => 'Voiture',
 'leisures'                 => 'Loisirs',
 'sport'                    => 'Sports',
 'travel'                   => 'Voyages',
 'tennis'                   => 'Tennis',
 'squash'                   => 'Squash',
 'windsurf'                 => 'Planche a Voile',
 'programming'              => 'Programmation',
 'roleplaying'              => 'Jeux de Rôle',
 'CA'                       => 'Canada',
 'UK'                       => 'Royaume-Unis',
 'USA'                      => 'Etat-Unis',
 'CR'                       => 'Costa-Rica',
 'IT'                       => 'Italie',
 'SP'                       => 'Espagne',
 'GR'                       => 'Gréce',
 'month'                    => 'Mois',
 'inprogress'               => 'En cours',
 'salesman'                 => 'Vendeur',
 'journalist'               => 'Journaliste',
 'animator'                 => 'Animateur',
 'years'                    => 'ans',
 'download'                 => 'Liens',
 'MSN'                      => 'MSN/Live Messenger',
 'Skype'                    => 'Skype',
 'ICQ'                      => 'ICQ / AIM',
 'Jabber'                   => 'Jabber / Google Talk',
);

?>