<?php

$lang = array(
 'presentation'             => 'Presentation',
 'competence'               => 'Knowledge',
 'experience'               => 'Experiences',
 'formation'                => 'Studies',
 'other'                    => 'Others',

 'knowledge_datapreocessing'=> 'Data-Processing Knowledge',
 'experience_professionnel' => 'Professional Experiences',

 'programming_languages'    => 'Programming Languages',
 'operating_systems'        => 'Operating systems',
 'system_administration'    => 'System Administration',
 'databases'                => 'Databases',
 'method'                   => 'Method',
 'software'                 => 'Software',
 'API__TECHNO'              => 'API / Technology',

 'concept'                  => 'concept',
 'schoolofcomputerengineer' => 'School of computer engineer',
 'notfinishedformation'     => 'Not finished formation',
 'businessdataprocessing'   => 'Business Data Processing',
 'during1years'             => 'during 1 years',
 'technicalcommercial'      => 'Technical-Commercial',

 'nationality'              => 'Nationality',
 'lastname'                 => 'Last Name',
 'firstname'                => 'First Name',
 'age'                      => 'Age',
 'birthdate'                => 'Date of birth',
 'birthplace'               => 'Birthplace',
 'address'                  => 'Address',
 'homephone'                => 'Telephone (home)',
 'portphone'                => 'Telephone (portable)',
 'email'                    => 'E-mail',
 'yearold'                  => 'years old',
 'company'                  => 'Company',
 'activity'                 => 'Activity',
 'technology'               => 'Technology',
 'mission'                  => 'Mission',
 'language'                 => 'Language',
 'english'                  => 'English',
 'spanish'                  => 'Spanish',
 'school'                   => 'School',
 'technical'                => 'Technical',
 'licence'                  => 'Licences',
 'moto'                     => 'moto',
 'car'                      => 'car',
 'leisures'                 => 'Leisures',
 'sport'                    => 'Sport',
 'travel'                   => 'Travel',
 'tennis'                   => 'Tennis',
 'squash'                   => 'Squash',
 'windsurf'                 => 'WindSurf',
 'programming'              => 'Programming',
 'roleplaying'              => 'Roleplaying',
 'CA'                       => 'Canada',
 'UK'                       => 'United Kingdom',
 'USA'                      => 'USA',
 'CR'                       => 'Costa-Rica',
 'IT'                       => 'Italy',
 'SP'                       => 'Spain',
 'GR'                       => 'Greece',
 'month'                    => 'Month',
 'inprogress'               => 'In Progress',
 'salesman'                 => 'Salesman',
 'journalist'               => 'Journalist',
 'animator'                 => 'Animator',
 'years'                    => 'years',
 'download'                 => 'Download',
 'MSN'                      => 'MSN/Live Messenger',
 'Skype'                    => 'Skype',
 'ICQ'                      => 'ICQ / AIM',
 'Jabber'                   => 'Jabber / Google Talk',
);

?>
