<?php

$lang = array(
 'presentation'             => 'Presentación',
 'competence'               => 'Capacidades',
 'experience'               => 'Experiencias',
 'formation'                => 'Estudios',
 'other'                    => 'Otros',

 'knowledge_datapreocessing'=> 'Capacidad Profesional',
 'experience_professionnel' => 'Experiencias profesionales',

 'programming_languages'    => 'Lenguajes de programación',
 'operating_systems'        => 'Sistemas operativos',
 'system_administration'    => 'Administración del sistema',
 'databases'                => 'Base de datos',
 'method'                   => 'Método',
 'software'                 => 'Software',
 'API__TECHNO'              => 'API / Tecnología',

 'concept'                  => 'concepto',
 'schoolofcomputerengineer' => 'Escuela del ingeniero informático',
 'notfinishedformation'     => 'Formación no acabada',
 'businessdataprocessing'   => 'Informática de negocio',
 'during1years'             => 'durante 1 año',
 'technicalcommercial'      => 'Técnico-Comercial',

 'nationality'              => 'Nacionalidad',
 'lastname'                 => 'Nombre',
 'firstname'                => 'Nombre',
 'age'                      => 'Edad',
 'birthdate'                => 'Fecha de nacimiento',
 'birthplace'               => 'Lugar de nacimiento',
 'address'                  => 'Dirección',
 'homephone'                => 'Teléfono (casa)',
 'portphone'                => 'Teléfono (cellular)',
 'email'                    => 'E-mail',
 'yearold'                  => 'años',
 'company'                  => 'Compañía',
 'activity'                 => 'Actividad',
 'technology'               => 'Tecnología',
 'mission'                  => 'Misión',
 'language'                 => 'Lengua',
 'english'                  => 'Inglés',
 'spanish'                  => 'Español',
 'school'                   => 'Escuela',
 'technical'                => 'Técnico',
 'licence'                  => 'Licencias',
 'moto'                     => 'moto',
 'car'                      => 'coche',
 'leisures'                 => 'Ocios',
 'sport'                    => 'Deporte',
 'travel'                   => 'Recorrido',
 'tennis'                   => 'Tenis',
 'squash'                   => 'Calabaza',
 'windsurf'                 => 'WindSurf',
 'programming'              => 'Programación',
 'roleplaying'              => 'Actuación de papeles',
 'CA'                       => 'Canadá',
 'UK'                       => 'Reino Unido',
 'USA'                      => 'USA',
 'CR'                       => 'Costa-Rica',
 'IT'                       => 'Italia',
 'SP'                       => 'España',
 'GR'                       => 'Grecia',
 'month'                    => 'Mes',
 'inprogress'               => 'En marcha',
 'salesman'                 => 'Vendedor',
 'journalist'               => 'Periodista',
 'animator'                 => 'Animador',
 'download'                 => 'Download',
 'MSN'                      => 'MSN/Live Messenger',
 'Skype'                    => 'Skype',
 'ICQ'                      => 'ICQ / AIM',
 'Jabber'                   => 'Jabber / Google Talk',
);

?>